### PR TITLE
separate process to load the airport data and defining the Aircraft type

### PR DESCRIPTION
**Pull request by Gunduran**
Loading the aircraft will be done in a separate process monitored by a separate flightloop. Tried to modify the original UI as less as possible.
Furthermore added a CSV file with the aircraft codes to classify them correcty.

### CODE REVIEW

**Comment by devleaks** [comment]
Thanks for the PR. Please test extensively before submitting PR. I hope there won't be any problem when airport is not found or has no taxiways.
Your other proposed modification look promising!

**Comment by devleaks** [comment]
I'll do some cleanup and change version number at the next release. Thanks.

**Comment by Gunduran** [comment]
Many thanks for the flowers :-) Regarding the testing, I did some tests on German airports with or without custom airports, mainly.
I didn't test the approach sequence arriving at smaller airports without taxiways. But looking to the logic, the pure load process is not really different than before.
I'll continue the next time on the taxiway representation (e.g. when leaving Cologne Rwy 14L via A2, A, Cross-RW 24, D, T....) to make this also displayed in the ui, when the route found. And far beyond I think about a scratchpad to allow entering the desired / ATC advised taxiway.

**Comment by Gunduran** [comment]
One additional comment: I've created the Readme.md file first, now it is displayed on GitHub as the main description not really mentionning you as the main author... Perhaps it is a good idea to rework it a bit :-)

**Comment by devleaks** [comment]
Don’t worry. I’ll fix that. Nobody’s reading anyway.😃

**Pull request merged**
